### ISSUE TITLE
Sir, is ComboToolplus not supporting the sop8 test clip line?

### ISSUE THREAD

**Issue by iisnsb** [YTEC-info/CH341A-Softwares#10]
Sir, is ComboToolplus not supporting the sop8 test clip line?As soon as I connect the flash chip with the sop8 test clip cable, it automatically flashes.

**Comment by YTEC-info** [comment]
It is often necessary to unsolder the chip and flash it directly connected to CH341, the motherboard circuit can hinder the flashing. Combotoolplus is not updated and does not have reliable support for chips larger than 8mb, I strongly recommend using the Windows or Linux options (flashrom, IMSProg, Neoprogrammer).
