### ISSUE TITLE
CH341EVT examples

### ISSUE THREAD

**Issue by otofoto** [YTEC-info/CH341A-Softwares#2]
Translated CH341EVT example GUI to English.

CH341CFG.EXE: modify data in external EEPROM and redefine
chip function and various identification information of CH341 

CH341EVT.EXE - evaluation board and example uses

[CH341EVT.zip](https://github.com/YTEC-info/CH341A-Softwares/files/7929313/CH341EVT.zip)

**Comment by YTEC-info** [comment]
Thanks for sharing, I've already added it to the software list
