### ISSUE TITLE
驱动问题？

### ISSUE THREAD

**Issue by xdcabc** [YTEC-info/CH341A-Softwares#3]
![Screenshot_20230503_201453_com appcombo ch341p](https://user-images.githubusercontent.com/41458224/235912726-acc2743d-599e-443e-a347-14318ea56621.jpg)
请问上图软件如何使用呢？
![Screenshot_20230503_201458_cn wch wchuartdemo](https://user-images.githubusercontent.com/41458224/235912749-5cf6c78a-4b28-4cf7-8a0f-42dbb15d7432.jpg)
这个软件点击添加设备则弹出无驱动？

**Comment by xdcabc** [comment]
是扫描设备

**Comment by YTEC-info** [comment]
ComboToolPlus: SPI and I2C, when connecting the CH341A to the smartphone, the app opens automatically, there are buttons to choose the chip model and the interface is very intuitive (I tested it only on Android 4.4 and 5.1)

CH34XUARTDEMO: UART only, I haven't tested it on my phone yet, I need a usb-c otg cable for that

See: [How to Connect and Use CH341A Mini USB Programmer with Smart Phone](https://www.youtube.com/watch?v=7mJ0sUIcTO8)

**Comment by xdcabc** [comment]
> 组合工具加： SPI和I2C，当CH341A连接到智能手机时，APP会自动打开，有选择芯片型号的按钮，界面非常直观（我只在Android 4.4和5.1上测试过）
> 
> CH34XUARTDEMO ：只有UART ，我还没有在手机上测试过，我需要一根usb-c otg电缆
> 
> 请参阅： [如何连接和使用CH341A迷你USB编程器与智能手机](https://www.youtube.com/watch?v=7mJ0sUIcTO8)

我尝试按照视频操作了，但是仍然没反应
