### ISSUE TITLE
How can I flash a new bios？

### ISSUE THREAD

**Issue by iisnsb** [YTEC-info/CH341A-Softwares#9]
My ch341a programmer hasn't arrived yet, and I don't see the feature to flash in comboToolplus.

**Comment by YTEC-info** [comment]
Features are only displayed after connecting ch341a to smartphone
![Screenshot_20240727-150032](https://github.com/user-attachments/assets/e2736e1d-9fc2-4be6-9a37-2b51d4b5915e)

**Comment by iisnsb** [comment]
Thank you,sir
